---
# Variable Defaults for `asymworks.baseline.core`

# Default Timezone is Los Angeles
timezone: America/Los_Angeles

# Default NTP Server
ntp_server: time.nist.gov
ntp_bootstrap: false

# Firewall Setup
ufw_enabled: true
ufw_ipv6: false
ufw_logging: false
ufw_policy: deny
ufw_ssh_appname: >-
  {{
      'OpenSSH'
        if ansible_facts['distribution']|lower == 'ubuntu'
        else 'SSH'
  }}

# mSMTP Setup
msmtp_enabled: false
msmtp_accounts:
  - name: default
    sender: username@gmail.com
    host: smtp.gmail.com
    port: 587
    tls: true
    auth: true
    username: username@gmail.com
    password: app-password

# mSMTP Default Sender Account
msmtp_default_account: default

# Restic Setup
restic_enabled: true

restic_repository_uri:
restic_repository_key:
restic_repository_env:

restic_notify_cmd:
restic_forget:
  daily: 7
  weekly: 4
  monthly: 6

restic_periodic_dir: >-
  {{
    '/etc/periodic/daily'
      if ansible_facts['os_family']|lower == 'alpine'
      else '/etc/cron.daily'
  }}
