---
# Debian-Specific Tasks for kraussnet.common

# Ensure Debian version is at least 9
- name: Asymworks Baseline (Debian) | Check Version
  when: ansible_distribution_version is version('9', '<')
  ansible.builtin.fail:
    msg: 'Unsupported Debian Version {{ ansible_distribution_version }} - Please Upgrade to Stretch or later'

# Install Basic Packages
- name: Asymworks Baseline (Debian) | Install Core Packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - nfs-common
      - ntpsec
      - python3-bcrypt
      - python3-passlib
      - python3-pip
      - ufw
      - vim
    update_cache: true

# Install Restic and SQLite
- name: Asymworks Baseline (Debian) | Install Restic Packages
  ansible.builtin.apt:
    name:
      - restic
      - sqlite3
    state: "{{ 'present' if restic_enabled else 'absent' }}"

# Install mSMTP Packages
- name: Asymworks Baseline (Debian) | Install mSMTP Packages
  ansible.builtin.apt:
    name:
      - msmtp
      - msmtp-mta
    state: "{{ 'present' if msmtp_enabled else 'absent' }}"

# Set System Timezone
- name: Asymworks Baseline (Debian) | Set Timezone
  community.general.timezone:
    name: "{{ timezone }}"

# Setup NTP Server
- name: Asymworks Baseline (Debian) | Reset Network Time Servers
  ansible.builtin.lineinfile:
    path: /etc/ntpsec/ntp.conf
    search_string: 'pool.ntp.org'
    state: absent
  notify:
    - Asymworks Baseline (Debian) | Restart ntpd

- name: Asymworks Baseline (Debian) | Set Network Time Server
  ansible.builtin.lineinfile:
    path: /etc/ntpsec/ntp.conf
    regex: "^server "
    line: "server {{ ntp_server }}"
  notify:
    - Asymworks Baseline (Debian) | Restart ntpd

- name: Asymworks Baseline (Debian) | Start Network Time Service
  ansible.builtin.service:
    name: ntp
    enabled: true
    state: started

# Ensure Cron Service is Running/Enabled
- name: Asymworks Baseline (Debian) | Enable Cron Daemon
  ansible.builtin.service:
    name: cron
    enabled: true
    state: started
