---

namespace: asymworks
name: core
version: 1.1.1
readme: README.md
authors:
  - Jonathan Krauss <jkrauss@asymworks.com>
description: Baseline configuration and software installation of server systems
license:
  - MIT

repository: https://github.com/asymworks/ansible-collections

# Tags
tags: [infrastructure, tools]

# Requirements
dependencies:
  "community.general": ">=7.0.0"
