---
# Alpine-Specific Tasks for asymworks.docker.common

# Install Docker
- name: Asymworks Docker (Alpine) | Install Docker
  community.general.apk:
    name:
      - docker
      - py3-pip
    update_cache: true

# Persist /srv in LBU
- name: Asymworks Docker (Alpine) | Persist /srv  # noqa: no-changed-when
  ansible.builtin.command:
    cmd: lbu include /srv
  when: alpine_diskless
  become: true

# Install Python Docker SDK
- name: Asymworks Docker (Alpine) | Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
